### ISSUE TITLE
Problema ao rodar

### ISSUE THREAD

**Issue by lokize** [wesleyegberto/javaee8-jsf-chat#4]
Bom dia, muito legal seu projeto, estou com um problema ao rodar com o Tomcat.

BUILD SUCCESS
------------------------------------------------------------------------
Total time: 4.656s
Finished at: Mon Jan 13 12:05:34 BRST 2020
Final Memory: 10M/153M
------------------------------------------------------------------------
Deploying on Apache Tomcat ou TomEE
    profile mode: false
    debug mode: false
    force redeploy: true
[Fatal Error] :4:6: A string "--" não é permitida nos comentários.

notei que no context é que se configura pra funcionar com o Tomcat, porém não sei como fazê-lo...

**Comment by lokize** [comment]
a propósito, muito legal o seu projeto...

**Comment by wesleyegberto** [comment]
Para rodar no tomcat você precisa descomentar todo o conteúdo do `<Context>` no arquivo Context.xml e adicionar as libs no pom.xml (devido ao uso do servidor EE utilizei apenas referência à API).
