### ISSUE TITLE
TomEE 8 context.xml error

### ISSUE THREAD

**Issue by rfincher** [wesleyegberto/javaee8-jsf-chat#5]
I get an error running on TomEE 8: "Cannot deploy the module. The context.xml file seems to be broken. Check whether it is well-formed and valid".

I uncommented the commented out sectiopn there, but no luck.

**Comment by wesleyegberto** [comment]
Hi

TomEE only supports Jakarta EE 8 which is using `javax` namespaces.

I've created [this branch](https://github.com/wesleyegberto/jakartaee-jsf-chat/tree/tomee-8) to show how to use with TomEE.
